# -*- mode: ruby -*-
# vi: set ft=ruby :

# Maquinas com imagem debian
vmsdeb = {
  'intranet' => {'memory' => '384', 'cpu' => 1, 'ip' => '40'},
  'datacenter' => {'memory' => '384', 'cpu' => 1, 'ip' => '42'},
}

# Maquinas com imagem centos
vmscts = {
  'master' => {'memory' => '2048', 'cpu' => 2, 'ip' => '150'},
  'node1' => {'memory' => '512', 'cpu' => 1, 'ip' => '151'},
  'node2' => {'memory' => '512', 'cpu' => 1, 'ip' => '152'},
}

Vagrant.configure("2") do |config|

  vmsdeb.each do |name, conf|
    config.vm.define "#{name}" do |d|
      d.vm.box = "geerlingguy/debian9"
      d.vm.box_check_update = false
      d.vm.hostname = "#{name}"
      d.vm.network "private_network", ip: "172.17.177.#{conf['ip']}"
      d.vm.provider "virtualbox" do |v|
        v.name = "#{name}"
        v.cpus = "#{conf['cpu']}"
        v.memory = "#{conf['memory']}"
      end
      d.vm.provision "shell", path: "update.sh"
      d.vm.provision "puppet" do |pup|
        pup.manifests_path = "manifests"
        pup.module_path = "modules"
        pup.manifest_file = "install.pp"
      end
    end
  end

  config.vm.define "controle" do |ans|
    ans.vm.box = "ansible/tower"
    ans.vm.box_check_update = false
    ans.vm.hostname = "controle"
    ans.vm.network "private_network", ip: "172.17.177.41"
    ans.vm.provider "virtualbox" do |vb|
      vb.name = "ansible"
      vb.memory = "1280"
    end
  end

  config.vm.define "gateway" do |gty|
    gty.vm.box = "geerlingguy/centos7"
    gty.vm.box_check_update = false
    gty.vm.hostname = "gateway"
    gty.vm.network "private_network", ip: "172.17.177.43"
    gty.vm.provision "shell", inline: "yum update -y && yum install epel-release -y"
    gty.vm.provider "virtualbox" do |vb|
      vb.name = "gateway"
      vb.cpus = 1
      vb.memory = "384"
    end
  end

  vmscts.each do |name, conf|
    config.vm.define "#{name}" do |k|
      k.vm.box = "geerlingguy/centos7"
      k.vm.box_check_update = false
      k.vm.network "public_network", ip: "192.168.0.#{conf['ip']}"
      k.vm.hostname = "#{name}"
      k.vm.provision "shell", inline: "yum update -y && yum install epel-release -y"
      k.vm.provider "virtualbox" do |v|
        v.name = "#{name}"
        v.cpus = "#{conf['cpu']}"
        v.memory = "#{conf['memory']}"
      end
    end
  end
end
